---
- set_fact:
    root_password: "{{ lookup('file', '{{ item }}') }}"
  with_first_found:
    - files:
        - ~/.config/harem/root_password
      errors: ignore

- name: generate random root password if not defined
  set_fact:
    root_password: |
      {{ lookup('password',
      '~/.config/harem/root_password chars=ascii_letters') }}
  when: root_password is not defined
  no_log: true

- become: true
  block:
    - name: boot tftp server speed
      # https://forum.synology.com/enu/viewtopic.php?t=107882
      ini_file:
        path: /etc/opentftp.ini
        section: TFTP-OPTIONS
        option: blksize
        value: "4096"
        # value: 1456
        no_extra_spaces: true
      register: result

    - name: restart tftp
      command: /usr/syno/sbin/synoservicectl --restart opentftp
      when: result is changed

    - name: configure default pxe boot menu
      vars:
        inventory_hostname: ~
      template:
        src: pxelinux.cfg/default.j2
        dest: "{{ pxe_root }}/pxelinux.cfg/default"

    - name: generate pxeboot menu
      syncronize:
        src: secrets/pxe
        dest: "{{ pxe_root }}/pxelinux.cfg/01-{{ ks_host_id }}"

    - name: deploy kickstart templated files (ks)
      template:
        src: "{{ ks_file }}"
        dest: "{{ ks_root }}/{{ (ks_file | basename | splitext)[0] }}"
        decrypt: true
      with_fileglob: templates/ks/*.ks.j2
      loop_control:
        loop_var: ks_file

    - name: deploy static files used during provisioning
      copy:
        src: "{{ ks_file }}"
        dest: "{{ ks_root }}"
      with_fileglob: files/etc/ssh/*
      loop_control:
        loop_var: ks_file

    - name: create directories for boot files
      file:
        path: "{{ pxe_root }}/{{ dir}}"
        state: directory
      with_items:
        - fedora28
        - centos7
        - rhel8
      loop_control:
        loop_var: dir

    - name: get ipxe
      get_url:
        url: "{{ file.value }}"
        dest: "{{ pxe_root }}/{{ file.key }}"
      with_dict:
        ipxe.pxe: http://boot.ipxe.org/ipxe.pxe
        undionly.kpxe: http://boot.ipxe.org/undionly.kpxe
        nemo.img: http://www.lsc-group.phys.uwm.edu/beowulf/nemo/construction/BIOS/Nemo-node-config.img
        memtest: http://boot.ipxe.org/memtest
        memtest.0: http://boot.ipxe.org/memtest.0
        'fedora28/vmlinuz': "{{ distros_mirror }}/fedora/linux/releases/28/Server/x86_64/os/images/pxeboot/vmlinuz"
        'fedora28/initrd.img': "{{ distros_mirror }}/fedora/linux/releases/28/Server/x86_64/os/images/pxeboot/initrd.img"
        'centos7/initrd.img': "{{ distros_mirror }}/centos/7/os/x86_64/images/pxeboot/initrd.img"
        'centos7/vmlinuz': "{{ distros_mirror }}/centos/7/os/x86_64/images/pxeboot/vmlinuz"
        'rhel8/vmlinuz': "{{ rhel8_pxeboot_url }}/vmlinuz"
        'rhel8/initrd.img': "{{ rhel8_pxeboot_url }}/initrd.img"
        'rhel80/vmlinuz': "http://download.eng.brq.redhat.com/rhel-8/rel-eng/RHEL-8/latest-RHEL-8.0/compose/BaseOS/x86_64/os/images/pxeboot/vmlinuz"
        'rhel80/initrd.img': "http://download.eng.brq.redhat.com/rhel-8/rel-eng/RHEL-8/latest-RHEL-8.0/compose/BaseOS/x86_64/os/images/pxeboot/initrd.img"


      loop_control:
        loop_var: file
