---
# like example.com
domain: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63343539343733633364303535313331363134353362373033613764376264646533613661356564
  6332303662323739376431653661333033393836343530640a663764383566353936353666383664
  66663565633865303134363530633934646230663163343231613232636231653538346230313962
  3439663737653638620a623634613831663735336538323863623034393962356261636531313939
  6662

syslog_server: syslog.lan

http_proxy_no_schema: 192.168.33.1:3128
https_proxy_no_schema: 192.168.33.1:3129
http_proxy: "http://{{ http_proxy_no_schema }}"
https_proxy: "http://{{ https_proxy_no_schema }}"
no_proxy: "localhost,zuul.openstack.org,192.168.0.0/16,10.0.0.0/8,172.30.0.0/16"

matrix_fqdn: "m.{{ domain }}"

vpn_username: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39633066656466343265663464623261336336316639316239363139626461366437643362366438
  6531633539333036396666633939303632613862306138360a326133636437393239363335613935
  64623632646432303862353433613963663463386436656538656331633266346465313665623562
  3939343034373735330a646433346265616363326364663235663437386638656662366665313731
  6262

vpn_otp_pin: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35343633343561323264353838323265633163653761323737346161616532363937333130323633
  3633346461303665643335343133313337353033616238320a336137393466303661313762356131
  35643464346262373033386234343632363631323633363639383865616163333435303236313635
  6632666233653937390a343037633938623465353665353937396161663164313761666166363237
  3661

vpn_otp_seed: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38313465306137653065633936613362383337336335313838623036653365373566656535323139
  6233326230633034653930316135653662333763626537330a343830363162646635303264646531
  31613665383666356366373931633134396136356532363635326161613966343764666366316333
  6365663064613637350a663663303834393836326533383833306530356363363165353366363430
  63313638653130656661643531393166333237633365616134663036656165383739613039346661
  3134313234373437636537363962346664396562356563666266

root_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39346134616534316266363266616162653132383732653062396332306238636463646336303766
  3936316565383865313363653366663563343338323464310a366639303264356563643538663161
  36636234333632643436353763616436316439373230393566653164376532383533663632366430
  6366613339643239360a323832396662383637626132303631636438323561303237353366393333
  3737

custom_ca: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34396338373264336639323034626666376532613537306433356164643839343833643339306332
  3066336261633732383636313262636534633833643734660a633765346461353466626239616463
  62623463633731393962383832343730343935666361383233333235323430613432346134303862
  3361303163633638650a393535656563353939623264663365396663373339663463333565393135
  65333465653836643961623933333138373938313962306361623465346535613235643432333831
  61303562393032656565626164666537613534636236336636386232636531376336366661636332
  31646231636238656334336566343765333230646339623462383966326330383034316261323763
  62643638363536623062643939303834363831396366663861346130623963373430363430333664
  64336238653534396532323632363537333430363361376164386264343333373064623365653161
  30346535636562643266323933323238373432656463663539653666356565323038653564393039
  65326337643161633565643838646330653465353233346338653662313235366564313030386461
  39633565383831353930336134626632353361646336376535353564376631633565326434333236
  62333736363564636230616638333961626562336164613737343762376339653438623262376136
  35323139396364326231373230386431316164643736666439373561326365626234653230656665
  39316635316462626263666539373934393263313663373139366333653363656438353366393664
  34623464643636313838633464343264306265383264356238396263663730303737303932393635
  65646435666530376165636365386436373034366231336264376163393265653734373538386638
  37346338616563366238656636356230623934356230633562373164373161356139613364633165
  30376335393735643536373466376261316431666535393962626634313163663738663235363265
  36633234376534316463663234613264613434343430656532303333663734393038323430383735
  62313433323662386533643635646235353533363563656164333363643630386638313363353963
  33326633396433323466663536393961373735333861663461663566326333656336373639333532
  31656461356663323666393239303130363836356364643863363464653536343630313630353561
  32386632653863303633373836353266313835303565333762383732666530303331313361356438
  66656364646233306365326662643032353364396665373366313561653133333762323738633237
  66326134396133336330303163363837393731613134666433386361653862393635646436616363
  38666338666465363238616132333430376638336362373163366237346464616461386338386162
  65633438313864623033633633383139633036373233346266363437343532386465346262336532
  37663561313034353332626133316638323233393364623635346666373036316164666362373166
  39663636663031303439326163633436366261333732353232323461363366316565303734653739
  61323966396461633436643538623835383337626333313039356639376263653266393834396234
  38353562333136643363623162323864656234656639633935623862633965336266316461633030
  34326665343564663664393862343238646661636434663466323562613265306161653635306638
  39393234323962323338613839393435663562336565396361616533626566386237616630623331
  64303135646363643335343865633538303835653165656432666365626533303032646237383037
  65386164393031643465376361376633376139626633333266373361333665343738373465626439
  62316164396464663530316539663161636439396166633335396330303163343831623864643733
  31376439313031633534393065353861313036663664393665623064316333383036363032393230
  62663437346331323565653036613066313331356462373261633435393834383037373764663531
  36306230626434333664633230643035623531396565373231323132363938646538633536616130
  39316264366237636436626665663337323163373034653865626666326533353237373537343534
  62313062373266663833366435373834323738313230376234363938643832316235393266306463
  38636438316332623238353262336666363639633861303165333565363865346462613063313530
  30316630623737353864356165633330366339333431346238666462336438356537613336663333
  37333939336663643062333731363838643961623035616430313666666362623139633635663231
  64616262346533643463316563363264346263303166663465303239353461363937346433356566
  37653363613863316539386231366535323762616666363836623038653862663733333964633366
  32316635613330333837666539366439333335626232663262353732376431613332313663613933
  65313932623732376530333134363163623762626235373264373931313131336637396663346561
  33656439313430633035313938336561653662636133386439653639333034306466613365333436
  61333435373436616263393131656435363964393630373662363830313765333634396166633662
  32336665636137653239373031323939353935623239616336653566323134643962623666643030
  66626432623563643535623566666639646564633132346630333735653361303434636331323430
  30323266326538313734313138356266353239343438303030623766343031366439613365653631
  38303037663334633339313734306463373663656162313265636333393533396234333431373332
  33626662356262636565613630346338323561313661623332396534663834373061323039646431
  37656364326231636134373937623033633138313031363836643438313163616662313834633939
  30303036306361663730363838623433343365623266656561383232313034356632646563343461
  38366361333935323365613839646363336566666339366665353635393466346561613563356234
  64336465643339376430643136306364323562373637646536383865333432386564313931376534
  62396161303732333736343738643363626331326262663230383235363064386365316561303061
  63323734366139633761303536643762663362653030653639623436323530626663356637333234
  62613562613536636163656566356562356437303966373463396633626432333830363366643931
  37643135396232346133366566323939373664643464663661366439623534613165633362633033
  36623837636635393537336432333939333037333439646633616266623363363663353835303436
  64373735316337333136363565663635356162343131616639366139646438656466363565343931
  33623165373331356261353134646237353435343830343365616331326130663739326663653231
  66663535363633643565623164386330333033653036353461373134316139353139363339656266
  31643231393863643862343536633738626166613833303131623638303462626332613137653465
  33333161643737323964613238323863333431636361326463316131633335313261646532313964
  38616362353630356635363837373633363665386230656463383837373334316164323233623036
  39653732313864373138316137386637373632343461613336326164323230626532383137366236
  32373464653336363730636263373439376664396665623632373834613461316361656532623533
  31393639353462333865323433323934333138633039643037643833333838666434646535323135
  35633434383632616431393239353938643463623333396162306363333861356332366237633363
  30363334636536306330366539303364383930633737343936313561326364633138633630316461
  33376438346564353966303031386364316136313131343565643666386333346631396636366635
  63633062363230333161306466336431653535366663343831666630353836623263303730663033
  64343336633831326336643032636564386133316363343364313134316261666363626562303134
  37346130663862653565633336363933326630353333626565613931373833383938363466376530
  63376338643466396337663065663163663831336335323434616664383839633064396635336466
  61616131626339353233323763616234393533333265613234376136326463353338613566393638
  37323831383233366139613838653532643131376265633936646630323631373036336636383765
  38393463623561343633373435666265343162626161633036383635643464616464653165386439
  38376332623662343731333738366637373162366562353932646664343337373565626463633636
  34653265333132613138613631356561363830316131336333626232316238623866363461326133
  39613462323438306366636266633163663665313231373331626539343037373034356637333362
  32323036363439306135663736343465616134393862613837353865643339363036316366396236
  65663234633330386134626638316136366637383930363234333666376335343331613434393361
  61343466393662343066313535623937643030633465643438303262323565656136663733613062
  39303661333261383538383636613539346263323266663132333861663038373233386639376536
  31663035643037626432383332613362646461333534623330633435613861646232316463666637
  65656561363262393733313665373461316461666630356335363937373262346335323732383862
  61663032336365663338636164366262626339376130623936663434306635383039376639396164
  35393165356532323330316163353336623739396161383838376162323063393938353463343337
  38653061323564323434663036636437343035653565303461336163353465366563656230376636
  30313230343362303233646232366163343930396238653839663339376439326261633235376466
  35356363613234323231636531663761326664646361333166636633666538376365666637396430
  63613661353663393637623466353835343862646130666437376366373338316566626233613630
  66613733313437363133316462646162663433323865346663633863663964623461326363396566
  64323038336663326636383933626236383063386264303933343639333739623232626239313766
  36623333663838306236373665383134363266333238636130396232326132316662656435373837
  37323632653764316466663834666332613930613861303933313664353864643735613435626234
  65316633376537393037643761383565333736353136316631613034653335613163653839633035
  66386262643737393439353038623737623433396663313630343966376331666435386632653739
  35656632363564356434343865366132656466356363313961323437303737333133646231616433
  35373831393036396561646439613831663366353730343534396632386266386462343238326231
  63346430316538633737393265623036373965393461626561393930663539636137313433613062
  65663034643535376261623532313465636432643262363039366563303765623430656630633266
  37636164393534326166666365613537663839356636323736303766356434306361626631633164
  373330306539373136333261303937356261


## Directory where etcd data stored
etcd_data_dir: /var/lib/etcd

## Directory where the binaries will be installed
bin_dir: /usr/local/bin

## The access_ip variable is used to define how other nodes should access
## the node.  This is used in flannel to allow other flannel nodes to see
## this node for example.  The access_ip is really useful AWS and Google
## environments where the nodes are accessed remotely by the "public" ip,
## but don't know about that address themselves.
#access_ip: 1.1.1.1


## External LB example config
## apiserver_loadbalancer_domain_name: "elb.some.domain"
#loadbalancer_apiserver:
#  address: 1.2.3.4
#  port: 1234

## Internal loadbalancers for apiservers
#loadbalancer_apiserver_localhost: true

## Local loadbalancer should use this port instead, if defined.
## Defaults to kube_apiserver_port (6443)
#nginx_kube_apiserver_port: 8443

### OTHER OPTIONAL VARIABLES
## For some things, kubelet needs to load kernel modules.  For example, dynamic kernel services are needed
## for mounting persistent volumes into containers.  These may not be loaded by preinstall kubernetes
## processes.  For example, ceph and rbd backed volumes.  Set to true to allow kubelet to load kernel
## modules.
#kubelet_load_modules: false

## Upstream dns servers used by dnsmasq
upstream_dns_servers:
 - 192.168.33.1
#  - 2a02:8010:61a9::1

## There are some changes specific to the cloud providers
## for instance we need to encapsulate packets with some network plugins
## If set the possible values are either 'gce', 'aws', 'azure', 'openstack', 'vsphere', 'oci', or 'external'
## When openstack is used make sure to source in the openstack credentials
## like you would do when using nova-client before starting the playbook.
## Note: The 'external' cloud provider is not supported.
## TODO(riverzhang): https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#running-cloud-controller-manager
#cloud_provider:

## Set these proxy values in order to update package manager and docker daemon to use proxies
#http_proxy: ""
#https_proxy: ""

## Refer to roles/kubespray-defaults/defaults/main.yml before modifying no_proxy
#no_proxy: ""

## Some problems may occur when downloading files over https proxy due to ansible bug
## https://github.com/ansible/ansible/issues/32750. Set this variable to False to disable
## SSL validation of get_url module. Note that kubespray will still be performing checksum validation.
#download_validate_certs: False

## If you need exclude all cluster nodes from proxy and other resources, add other resources here.
additional_no_proxy: "localhost,192.168.0.0/16,10.0.0.0/8,172.30.0.0/16"

## Certificate Management
## This setting determines whether certs are generated via scripts.
## Chose 'none' if you provide your own certificates.
## Option is  "script", "none"
## note: vault is removed
#cert_management: script

## Set to true to allow pre-checks to fail and continue deployment
#ignore_assert_errors: false

## The read-only port for the Kubelet to serve on with no authentication/authorization. Uncomment to enable.
#kube_read_only_port: 10255

## Set true to download and cache container
#download_container: true

## Deploy container engine
# Set false if you want to deploy container engine manually.
#deploy_container_engine: true

## Set Pypi repo and cert accordingly
#pyrepo_index: https://pypi.example.com/simple
#pyrepo_cert: /etc/ssl/certs/ca-certificates.crt
