---
host: chat.freenode.net
ssl_port: 6697
nick: recheck
alerts_channel: '##recheck-alerts'
mode:
feeds:
  "#ansible-molecule":
    so-molecule:
      url: https://stackoverflow.com/feeds/tag/molecule
      period: 0.5
      shorten: false
      new: none
    gh-ansible:
      url: https://github.com/ansible/ansible/releases.atom
      shorten: false
      new: none
    gh-molecule:
      url: https://github.com/ansible/molecule/releases.atom
      shorten: false
      new: none
    gh-pytest-molecule:
      url: https://github.com/pycontribs/pytest-molecule/releases.atom
      shorten: false
      new: none
    gh-selinux:
      url: https://github.com/pycontribs/selinux/releases.atom
      shorten: false
      new: none
    gh-molecule-goss:
      url: https://github.com/pycontribs/molecule-goss/releases.atom
      shorten: false
      new: none
    gh-molecule-azure:
      url: https://github.com/pycontribs/molecule-azure/releases.atom
      shorten: false
      new: none
    gh-cookiecutter:
      url: https://github.com/cookiecutter/cookiecutter/releases.atom
      shorten: false
      new: none
  "#oooq":
    taiga-blog:
      url: https://blog.taiga.io/feeds/all.atom.xml
      period: 0.5
      shorten: false
      new: none
    rdo-blog:
      url: https://blogs.rdoproject.org/feed/
      period: 0.5
      shorten: false
      new: none
    gh-ansible:
      url: https://github.com/ansible/ansible/releases.atom
      shorten: false
    gh-molecule:
      url: https://github.com/ansible/molecule/releases.atom
      shorten: false
    gh-pytest-molecule:
      url: https://github.com/pycontribs/pytest-molecule/releases.atom
      shorten: false
    gh-selinux:
      url: https://github.com/pycontribs/selinux/releases.atom
      shorten: false
  "#zuul":
    so-zuul:
      url: https://stackoverflow.com/feeds/tag/openstack-zuul
      period: 0.5
      shorten: false
      new: none
  "#openstack":
    so-openstack:
      url: https://stackoverflow.com/feeds/tag/openstack
      period: 0.5
      shorten: false
      new: none
  "#tripeo":
    ask-tripleo:
      url: https://ask.openstack.org/en/feeds/rss/?q=tripleo&tags=tripleo
      period: 0.5
      shorten: false
      new: none
    so-tripleo:
      url: https://stackoverflow.com/feeds/tag/tripleo
      period: 0.5
      shorten: false
      new: none
    sf-tripleo:
      url: https://serverfault.com/feeds/tag/tripleo
      period: 0.5
      shorten: false
      new: none
  "#openstack-jjb":
    so-jjb:
      url: https://stackoverflow.com/feeds/tag/jenkins-job-builder
      period: 0.5
      shorten: false
      new: none
  "#opendev":
    so-python-pbr:
      url: https://stackoverflow.com/feeds/tag/python-pbr
      period: 0.5
      shorten: false
      new: none
    so-git-review:
      url: https://stackoverflow.com/feeds/tag/git-review
      period: 0.5
      shorten: false
      new: none
  "#OPNsense":
    so-opnsense:
      url: https://stackoverflow.com/feeds/tag/opnsense
      period: 0.5
      shorten: false
      new: none
  "#quay":
    so-quay-io:
      url: https://stackoverflow.com/feeds/tag/quay.io
      period: 0.5
      shorten: false
      new: none
  "#podman":
    so-buildah:
      url: https://stackoverflow.com/feeds/tag/buildah
      period: 0.5
      shorten: false
      new: none
    so-podman:
      url: https://stackoverflow.com/feeds/tag/podman
      period: 0.5
      shorten: false
      new: none
  "#pylib":
    so-tox:
      url: https://stackoverflow.com/feeds/tag/tox
      period: 0.5
      shorten: false
      new: none
    so-pytest:
      url: https://stackoverflow.com/feeds/tag/pytest
      period: 3
      shorten: false
      new: none
    pre-commit:
      url: https://stackoverflow.com/feeds/tag/pre-commit.com
      period: 0.5
      shorten: false
    gh-testinfra:
      url: https://github.com/philpep/testinfra/releases.atom
      shorten: false
      new: none
  "#ara":
    so-ara:
      url: https://stackoverflow.com/feeds/tag/ara
  "#cookiecutter":
    gh-cookiecutter:
      url: https://github.com/cookiecutter/cookiecutter/releases.atom
      shorten: false
      new: none
